image: "docker.slock.it/build-images/node:10-alpine"
stages:
  - build
  - deploy

build-pkg:
  stage: build
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
  artifacts:
    name: build-js
    paths:
      - node_modules/ew-asset-registry-contracts
      - node_modules/ew-asset-registry-lib
      - node_modules/ew-market-contracts
      - node_modules/ew-origin-contracts
      - node_modules/ew-user-registry-contracts
      - node_modules/ew-user-registry-lib

push-to-public-git:
  stage: deploy
  only:
    - tags
  tags:
    - short-jobs
  dependencies:
    - build-pkg
  script:
    - echo -e "$CI_SSH_KEY_SLOCKIT" > /gitkey
    - chmod 0400 /gitkey
    - export GIT_SSH_COMMAND="/usr/bin/ssh -o StrictHostKeyChecking=no -oPort=2222 -i /gitkey"
    - git remote add external git@public-git.slock.it:sonnen/sonnen-lib.git
    - git config --global user.email "ci-bot@slock.it"
    - git config --global user.name "Slock.it CI Robot"
    - rm .gitignore
    - git add node_modules
    - git commit -am "[AUTO] add artifacts"
    - git push --force external HEAD:refs/heads/master
    - git push --force --tags external
